#############################################################################
# Makefile for building: Stylization
# Generated by qmake (3.0) (Qt 5.7.1)
# Project:  Stylization.pro
# Template: app
# Command: /Users/blinnbryce/Qt5.7.1/5.7/clang_64/bin/qmake -spec macx-clang CONFIG+=x86_64 -o Makefile Stylization.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_XML_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.8 -O2 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.8 -msse2 -O2 -std=gnu++11 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -Ilib -I../../../Qt5.7.1/5.7/clang_64/lib/QtGui.framework/Headers -I../../../Qt5.7.1/5.7/clang_64/lib/QtXml.framework/Headers -I../../../Qt5.7.1/5.7/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/AGL.framework/Headers -I../../../Qt5.7.1/5.7/clang_64/mkspecs/macx-clang -F/Users/blinnbryce/Qt5.7.1/5.7/clang_64/lib
QMAKE         = /Users/blinnbryce/Qt5.7.1/5.7/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Stylization1.0.0
DISTDIR = /Users/blinnbryce/Documents/2020/stylizing-video/.tmp/Stylization1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -stdlib=libc++ -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.8 -Wl,-rpath,/Users/blinnbryce/Qt5.7.1/5.7/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/blinnbryce/Qt5.7.1/5.7/clang_64/lib -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework QtXml -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/main.cpp 
OBJECTS       = main.o
DIST          = ../../../Qt5.7.1/5.7/clang_64/mkspecs/features/spec_pre.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/qdevice.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/device_config.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/common/unix.conf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/common/mac.conf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/common/macx.conf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/common/sanitize.conf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/common/gcc-base.conf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/common/clang.conf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/common/clang-mac.conf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/qconfig.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/qt_functions.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/qt_config.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/spec_post.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/toolchain.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/mac/toolchain.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/default_pre.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/resolve_config.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/default_post.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/warn_on.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/qt.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/resources.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/moc.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/unix/thread.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/file_copies.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/mac/rez.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/exceptions.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/yacc.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/lex.prf \
		Stylization.pro  src/main.cpp
QMAKE_TARGET  = Stylization
DESTDIR       = 
TARGET        = Stylization


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Stylization.pro ../../../Qt5.7.1/5.7/clang_64/mkspecs/macx-clang/qmake.conf ../../../Qt5.7.1/5.7/clang_64/mkspecs/features/spec_pre.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/qdevice.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/device_config.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/common/unix.conf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/common/mac.conf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/common/macx.conf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/common/sanitize.conf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/common/gcc-base.conf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/common/clang.conf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/common/clang-mac.conf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/qconfig.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/qt_functions.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/qt_config.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/spec_post.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/toolchain.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/mac/toolchain.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/default_pre.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/resolve_config.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/default_post.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/warn_on.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/qt.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/resources.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/moc.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/unix/thread.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/file_copies.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/mac/rez.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/exceptions.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/yacc.prf \
		../../../Qt5.7.1/5.7/clang_64/mkspecs/features/lex.prf \
		Stylization.pro \
		../../../Qt5.7.1/5.7/clang_64/lib/QtGui.framework/QtGui.prl \
		../../../Qt5.7.1/5.7/clang_64/lib/QtXml.framework/QtXml.prl \
		../../../Qt5.7.1/5.7/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec macx-clang CONFIG+=x86_64 -o Makefile Stylization.pro
../../../Qt5.7.1/5.7/clang_64/mkspecs/features/spec_pre.prf:
../../../Qt5.7.1/5.7/clang_64/mkspecs/qdevice.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/features/device_config.prf:
../../../Qt5.7.1/5.7/clang_64/mkspecs/common/unix.conf:
../../../Qt5.7.1/5.7/clang_64/mkspecs/common/mac.conf:
../../../Qt5.7.1/5.7/clang_64/mkspecs/common/macx.conf:
../../../Qt5.7.1/5.7/clang_64/mkspecs/common/sanitize.conf:
../../../Qt5.7.1/5.7/clang_64/mkspecs/common/gcc-base.conf:
../../../Qt5.7.1/5.7/clang_64/mkspecs/common/gcc-base-mac.conf:
../../../Qt5.7.1/5.7/clang_64/mkspecs/common/clang.conf:
../../../Qt5.7.1/5.7/clang_64/mkspecs/common/clang-mac.conf:
../../../Qt5.7.1/5.7/clang_64/mkspecs/qconfig.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_location.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_purchasing.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_script.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_scxml.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../Qt5.7.1/5.7/clang_64/mkspecs/features/qt_functions.prf:
../../../Qt5.7.1/5.7/clang_64/mkspecs/features/qt_config.prf:
../../../Qt5.7.1/5.7/clang_64/mkspecs/macx-clang/qmake.conf:
../../../Qt5.7.1/5.7/clang_64/mkspecs/features/spec_post.prf:
../../../Qt5.7.1/5.7/clang_64/mkspecs/features/exclusive_builds.prf:
../../../Qt5.7.1/5.7/clang_64/mkspecs/features/mac/sdk.prf:
../../../Qt5.7.1/5.7/clang_64/mkspecs/features/toolchain.prf:
../../../Qt5.7.1/5.7/clang_64/mkspecs/features/mac/toolchain.prf:
../../../Qt5.7.1/5.7/clang_64/mkspecs/features/default_pre.prf:
../../../Qt5.7.1/5.7/clang_64/mkspecs/features/mac/default_pre.prf:
../../../Qt5.7.1/5.7/clang_64/mkspecs/features/resolve_config.prf:
../../../Qt5.7.1/5.7/clang_64/mkspecs/features/default_post.prf:
../../../Qt5.7.1/5.7/clang_64/mkspecs/features/mac/default_post.prf:
../../../Qt5.7.1/5.7/clang_64/mkspecs/features/mac/objective_c.prf:
../../../Qt5.7.1/5.7/clang_64/mkspecs/features/warn_on.prf:
../../../Qt5.7.1/5.7/clang_64/mkspecs/features/qt.prf:
../../../Qt5.7.1/5.7/clang_64/mkspecs/features/resources.prf:
../../../Qt5.7.1/5.7/clang_64/mkspecs/features/moc.prf:
../../../Qt5.7.1/5.7/clang_64/mkspecs/features/unix/opengl.prf:
../../../Qt5.7.1/5.7/clang_64/mkspecs/features/unix/thread.prf:
../../../Qt5.7.1/5.7/clang_64/mkspecs/features/file_copies.prf:
../../../Qt5.7.1/5.7/clang_64/mkspecs/features/mac/rez.prf:
../../../Qt5.7.1/5.7/clang_64/mkspecs/features/mac/asset_catalogs.prf:
../../../Qt5.7.1/5.7/clang_64/mkspecs/features/testcase_targets.prf:
../../../Qt5.7.1/5.7/clang_64/mkspecs/features/exceptions.prf:
../../../Qt5.7.1/5.7/clang_64/mkspecs/features/yacc.prf:
../../../Qt5.7.1/5.7/clang_64/mkspecs/features/lex.prf:
Stylization.pro:
../../../Qt5.7.1/5.7/clang_64/lib/QtGui.framework/QtGui.prl:
../../../Qt5.7.1/5.7/clang_64/lib/QtXml.framework/QtXml.prl:
../../../Qt5.7.1/5.7/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=x86_64 -o Makefile Stylization.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents src/main.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: src/main.cpp ../../../Qt5.7.1/5.7/clang_64/lib/QtCore.framework/Headers/QCoreApplication \
		../../../Qt5.7.1/5.7/clang_64/lib/QtCore.framework/Headers/qcoreapplication.h \
		../../../Qt5.7.1/5.7/clang_64/lib/QtCore.framework/Headers/QCommandLineParser \
		../../../Qt5.7.1/5.7/clang_64/lib/QtCore.framework/Headers/qcommandlineparser.h \
		lib/Eigen/Core \
		lib/Eigen/src/Core/util/DisableStupidWarnings.h \
		lib/Eigen/src/Core/util/Macros.h \
		lib/Eigen/src/Core/util/MKL_support.h \
		lib/Eigen/src/misc/blas.h \
		lib/Eigen/src/Core/util/Constants.h \
		lib/Eigen/src/Core/util/Meta.h \
		lib/Eigen/src/Core/util/ForwardDeclarations.h \
		lib/Eigen/src/Core/util/StaticAssert.h \
		lib/Eigen/src/Core/util/XprHelper.h \
		lib/Eigen/src/Core/util/Memory.h \
		lib/Eigen/src/Core/NumTraits.h \
		lib/Eigen/src/Core/MathFunctions.h \
		lib/Eigen/src/Core/GenericPacketMath.h \
		lib/Eigen/src/Core/MathFunctionsImpl.h \
		lib/Eigen/src/Core/arch/SSE/PacketMath.h \
		lib/Eigen/src/Core/arch/AVX/PacketMath.h \
		lib/Eigen/src/Core/arch/AVX512/PacketMath.h \
		lib/Eigen/src/Core/arch/AVX512/MathFunctions.h \
		lib/Eigen/src/Core/arch/SSE/Complex.h \
		lib/Eigen/src/Core/arch/SSE/MathFunctions.h \
		lib/Eigen/src/Core/arch/AVX/MathFunctions.h \
		lib/Eigen/src/Core/arch/AVX/Complex.h \
		lib/Eigen/src/Core/arch/AVX/TypeCasting.h \
		lib/Eigen/src/Core/arch/SSE/TypeCasting.h \
		lib/Eigen/src/Core/arch/AltiVec/PacketMath.h \
		lib/Eigen/src/Core/arch/AltiVec/MathFunctions.h \
		lib/Eigen/src/Core/arch/AltiVec/Complex.h \
		lib/Eigen/src/Core/arch/NEON/PacketMath.h \
		lib/Eigen/src/Core/arch/NEON/MathFunctions.h \
		lib/Eigen/src/Core/arch/NEON/Complex.h \
		lib/Eigen/src/Core/arch/ZVector/PacketMath.h \
		lib/Eigen/src/Core/arch/ZVector/MathFunctions.h \
		lib/Eigen/src/Core/arch/ZVector/Complex.h \
		lib/Eigen/src/Core/arch/CUDA/Half.h \
		lib/Eigen/src/Core/arch/CUDA/PacketMathHalf.h \
		lib/Eigen/src/Core/arch/CUDA/TypeCasting.h \
		lib/Eigen/src/Core/arch/CUDA/PacketMath.h \
		lib/Eigen/src/Core/arch/CUDA/MathFunctions.h \
		lib/Eigen/src/Core/arch/Default/Settings.h \
		lib/Eigen/src/Core/functors/TernaryFunctors.h \
		lib/Eigen/src/Core/functors/BinaryFunctors.h \
		lib/Eigen/src/Core/functors/UnaryFunctors.h \
		lib/Eigen/src/Core/functors/NullaryFunctors.h \
		lib/Eigen/src/Core/functors/StlFunctors.h \
		lib/Eigen/src/Core/functors/AssignmentFunctors.h \
		lib/Eigen/src/Core/arch/CUDA/Complex.h \
		lib/Eigen/src/Core/IO.h \
		lib/Eigen/src/Core/DenseCoeffsBase.h \
		lib/Eigen/src/Core/DenseBase.h \
		lib/Eigen/src/plugins/BlockMethods.h \
		lib/Eigen/src/Core/MatrixBase.h \
		lib/Eigen/src/plugins/CommonCwiseUnaryOps.h \
		lib/Eigen/src/plugins/CommonCwiseBinaryOps.h \
		lib/Eigen/src/plugins/MatrixCwiseUnaryOps.h \
		lib/Eigen/src/plugins/MatrixCwiseBinaryOps.h \
		lib/Eigen/src/Core/EigenBase.h \
		lib/Eigen/src/Core/Product.h \
		lib/Eigen/src/Core/CoreEvaluators.h \
		lib/Eigen/src/Core/AssignEvaluator.h \
		lib/Eigen/src/Core/Assign.h \
		lib/Eigen/src/Core/ArrayBase.h \
		lib/Eigen/src/plugins/ArrayCwiseUnaryOps.h \
		lib/Eigen/src/plugins/ArrayCwiseBinaryOps.h \
		lib/Eigen/src/Core/util/BlasUtil.h \
		lib/Eigen/src/Core/DenseStorage.h \
		lib/Eigen/src/Core/NestByValue.h \
		lib/Eigen/src/Core/ReturnByValue.h \
		lib/Eigen/src/Core/NoAlias.h \
		lib/Eigen/src/Core/PlainObjectBase.h \
		lib/Eigen/src/Core/Matrix.h \
		lib/Eigen/src/Core/Array.h \
		lib/Eigen/src/Core/CwiseTernaryOp.h \
		lib/Eigen/src/Core/CwiseBinaryOp.h \
		lib/Eigen/src/Core/CwiseUnaryOp.h \
		lib/Eigen/src/Core/CwiseNullaryOp.h \
		lib/Eigen/src/Core/CwiseUnaryView.h \
		lib/Eigen/src/Core/SelfCwiseBinaryOp.h \
		lib/Eigen/src/Core/Dot.h \
		lib/Eigen/src/Core/StableNorm.h \
		lib/Eigen/src/Core/Stride.h \
		lib/Eigen/src/Core/MapBase.h \
		lib/Eigen/src/Core/Map.h \
		lib/Eigen/src/Core/Ref.h \
		lib/Eigen/src/Core/Block.h \
		lib/Eigen/src/Core/VectorBlock.h \
		lib/Eigen/src/Core/Transpose.h \
		lib/Eigen/src/Core/DiagonalMatrix.h \
		lib/Eigen/src/Core/Diagonal.h \
		lib/Eigen/src/Core/DiagonalProduct.h \
		lib/Eigen/src/Core/Redux.h \
		lib/Eigen/src/Core/Visitor.h \
		lib/Eigen/src/Core/Fuzzy.h \
		lib/Eigen/src/Core/Swap.h \
		lib/Eigen/src/Core/CommaInitializer.h \
		lib/Eigen/src/Core/GeneralProduct.h \
		lib/Eigen/src/Core/Solve.h \
		lib/Eigen/src/Core/Inverse.h \
		lib/Eigen/src/Core/SolverBase.h \
		lib/Eigen/src/Core/PermutationMatrix.h \
		lib/Eigen/src/Core/Transpositions.h \
		lib/Eigen/src/Core/TriangularMatrix.h \
		lib/Eigen/src/Core/SelfAdjointView.h \
		lib/Eigen/src/Core/products/GeneralBlockPanelKernel.h \
		lib/Eigen/src/Core/products/Parallelizer.h \
		lib/Eigen/src/Core/ProductEvaluators.h \
		lib/Eigen/src/Core/products/GeneralMatrixVector.h \
		lib/Eigen/src/Core/products/GeneralMatrixMatrix.h \
		lib/Eigen/src/Core/SolveTriangular.h \
		lib/Eigen/src/Core/products/GeneralMatrixMatrixTriangular.h \
		lib/Eigen/src/Core/products/SelfadjointMatrixVector.h \
		lib/Eigen/src/Core/products/SelfadjointMatrixMatrix.h \
		lib/Eigen/src/Core/products/SelfadjointProduct.h \
		lib/Eigen/src/Core/products/SelfadjointRank2Update.h \
		lib/Eigen/src/Core/products/TriangularMatrixVector.h \
		lib/Eigen/src/Core/products/TriangularMatrixMatrix.h \
		lib/Eigen/src/Core/products/TriangularSolverMatrix.h \
		lib/Eigen/src/Core/products/TriangularSolverVector.h \
		lib/Eigen/src/Core/BandMatrix.h \
		lib/Eigen/src/Core/CoreIterators.h \
		lib/Eigen/src/Core/ConditionEstimator.h \
		lib/Eigen/src/Core/BooleanRedux.h \
		lib/Eigen/src/Core/Select.h \
		lib/Eigen/src/Core/VectorwiseOp.h \
		lib/Eigen/src/Core/Random.h \
		lib/Eigen/src/Core/Replicate.h \
		lib/Eigen/src/Core/Reverse.h \
		lib/Eigen/src/Core/ArrayWrapper.h \
		lib/Eigen/src/Core/products/GeneralMatrixMatrix_BLAS.h \
		lib/Eigen/src/Core/products/GeneralMatrixVector_BLAS.h \
		lib/Eigen/src/Core/products/GeneralMatrixMatrixTriangular_BLAS.h \
		lib/Eigen/src/Core/products/SelfadjointMatrixMatrix_BLAS.h \
		lib/Eigen/src/Core/products/SelfadjointMatrixVector_BLAS.h \
		lib/Eigen/src/Core/products/TriangularMatrixMatrix_BLAS.h \
		lib/Eigen/src/Core/products/TriangularMatrixVector_BLAS.h \
		lib/Eigen/src/Core/products/TriangularSolverMatrix_BLAS.h \
		lib/Eigen/src/Core/Assign_MKL.h \
		lib/Eigen/src/Core/GlobalFunctions.h \
		lib/Eigen/src/Core/util/ReenableStupidWarnings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

